name: Update Production Branch

on:
  push:
    branches:
      - master

jobs:
  update-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Overwrite production branch with master
        run: |
          git fetch
          git switch production
          git reset --hard master
          git push --force origin production

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.0.0
        with:
          directory: 'static'
          output: 'static'
          add_suffix: false

      - name: Commit and push minified files to production
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Minify files for production"
          git push origin production
